### ISSUE TITLE
ModuleNotFoundError: No module named 'markupsafe._compat' when trying to run "python mange.py"

### ISSUE THREAD

**Issue by 97997** [OmkarPathak/A-Simple-Note-Taking-Web-App#3]
I get this error when trying to run manage.py. 
Not sure if I'm doing something wrong, I would appreciate your help.

`C:\git\A-Simple-Note-Taking-Web-App>python manage.py
Traceback (most recent call last):
  File "manage.py", line 1, in <module>
    from flask import (
  File "C:\Users\ekb\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\__init__.py", line 19, in <module>
    from jinja2 import Markup, escape
  File "C:\Users\ekb\AppData\Local\Programs\Python\Python36-32\lib\site-packages\jinja2\__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "C:\Users\ekb\AppData\Local\Programs\Python\Python36-32\lib\site-packages\jinja2\environment.py", line 15, in <module>
    from jinja2 import nodes
  File "C:\Users\ekb\AppData\Local\Programs\Python\Python36-32\lib\site-packages\jinja2\nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "C:\Users\ekb\AppData\Local\Programs\Python\Python36-32\lib\site-packages\jinja2\utils.py", line 624, in <module>
    from markupsafe import Markup, escape, soft_unicode
  File "C:\Users\ekb\AppData\Local\Programs\Python\Python36-32\lib\site-packages\markupsafe\__init__.py", line 14, in <module>
    from markupsafe._compat import text_type, string_types, int_types, \
ModuleNotFoundError: No module named 'markupsafe._compat'

C:\git\A-Simple-Note-Taking-Web-App>`

**Comment by 97997** [comment]
I solved the error by installing python 3.5.4, I was using python 3.6.
